### PR TITLE
trying PR to Keerthi

### PR DESCRIPTION
**Pull request by vinaykumarsrs**
uploading webapp to keerthi's github
to keerthi

### CODE REVIEW

**Review by kirthishr — COMMENTED** [review]
hi vinc 
fix the war file and then commit again
fuck off

**Comment by kirthishr** [comment]
hi vinc 
i reject this PR
fuck off

**Comment by vinaykumarsrs** [comment]
trying to push to keerthi's repo

**Comment by keeru147** [comment]
merged launch.sh

**Pull request merged**
